/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAkunRouteImport } from './routes/_authenticated/akun'
import { Route as AuthenticatedAkunProfilRouteImport } from './routes/_authenticated/akun.profil'
import { Route as AuthenticatedAkunAlamatRouteImport } from './routes/_authenticated/akun.alamat'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkunRoute = AuthenticatedAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkunProfilRoute = AuthenticatedAkunProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedAkunRoute,
} as any)
const AuthenticatedAkunAlamatRoute = AuthenticatedAkunAlamatRouteImport.update({
  id: '/alamat',
  path: '/alamat',
  getParentRoute: () => AuthenticatedAkunRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/akun': typeof AuthenticatedAkunRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/akun/alamat': typeof AuthenticatedAkunAlamatRoute
  '/akun/profil': typeof AuthenticatedAkunProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/akun': typeof AuthenticatedAkunRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/akun/alamat': typeof AuthenticatedAkunAlamatRoute
  '/akun/profil': typeof AuthenticatedAkunProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/_authenticated/akun': typeof AuthenticatedAkunRouteWithChildren
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/_authenticated/akun/alamat': typeof AuthenticatedAkunAlamatRoute
  '/_authenticated/akun/profil': typeof AuthenticatedAkunProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/shop'
    | '/akun'
    | '/cart'
    | '/produk/$slug'
    | '/akun/alamat'
    | '/akun/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/shop'
    | '/akun'
    | '/cart'
    | '/produk/$slug'
    | '/akun/alamat'
    | '/akun/profil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/shop'
    | '/_authenticated/akun'
    | '/_authenticated/cart'
    | '/produk/$slug'
    | '/_authenticated/akun/alamat'
    | '/_authenticated/akun/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akun': {
      id: '/_authenticated/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AuthenticatedAkunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akun/profil': {
      id: '/_authenticated/akun/profil'
      path: '/profil'
      fullPath: '/akun/profil'
      preLoaderRoute: typeof AuthenticatedAkunProfilRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
    '/_authenticated/akun/alamat': {
      id: '/_authenticated/akun/alamat'
      path: '/alamat'
      fullPath: '/akun/alamat'
      preLoaderRoute: typeof AuthenticatedAkunAlamatRouteImport
      parentRoute: typeof AuthenticatedAkunRoute
    }
  }
}

interface AuthenticatedAkunRouteChildren {
  AuthenticatedAkunAlamatRoute: typeof AuthenticatedAkunAlamatRoute
  AuthenticatedAkunProfilRoute: typeof AuthenticatedAkunProfilRoute
}

const AuthenticatedAkunRouteChildren: AuthenticatedAkunRouteChildren = {
  AuthenticatedAkunAlamatRoute: AuthenticatedAkunAlamatRoute,
  AuthenticatedAkunProfilRoute: AuthenticatedAkunProfilRoute,
}

const AuthenticatedAkunRouteWithChildren =
  AuthenticatedAkunRoute._addFileChildren(AuthenticatedAkunRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAkunRoute: typeof AuthenticatedAkunRouteWithChildren
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAkunRoute: AuthenticatedAkunRouteWithChildren,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  ProdukSlugRoute: ProdukSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
